package com.gig.zendo.ui.presentation.navigation

sealed class Screens(val route: String) {
    data object SplashScreen : Screens(route = "SplashScreen")
    data object LoginScreen : Screens(route = "LoginScreen")
    data object RegisterScreen : Screens(route = "RegisterScreen")
    data object GoogleLoginScreen : Screens(route = "GoogleLoginScreen")
    data object HouseScreen : Screens(route = "HouseScreen")
    data object CreateHouseScreen : Screens(route = "CreateHouseScreen")
    data object RoomScreen : Screens(route = "RoomScreen")
    data object InstructionScreen : Screens(route = "InstructionScreen")
    data object CreateRoomScreen : Screens(route = "CreateRoomScreen")
    data object ServiceScreen : Screens(route = "ServiceScreen")
    data object CreateTenantScreen : Screens(route = "CreateTenantScreen")
    data object CreateInvoiceScreen : Screens(route = "CreateInvoiceScreen")
    data object TenantHistoryScreen : Screens(route = "TenantHistoryScreen")
    data object TenantDetailScreen : Screens(route = "TenantDetailScreen")
    data object InvoiceHistoryScreen : Screens(route = "InvoiceHistoryScreen")
    data object AcceptInvoiceScreen : Screens(route = "AcceptInvoiceScreen")
    data object InvoiceDetailScreen : Screens(route = "InvoiceDetailScreen")
    data object ServiceRecordScreen : Screens(route = "ServiceRecordScreen")
    data object CreateExpenseRecordScreen : Screens(route = "CreateExpenseRecordScreen")
    data object ExpenseRecordScreen : Screens(route = "ExpenseRecordScreen")
    data object FinancialReportScreen: Screens(route = "FinancialReportScreen")
    data object SupportScreen : Screens(route = "SupportScreen")
    data object ChatbotScreen : Screens(route = "ChatbotScreen")
}